### ISSUE TITLE
Use TLS for RPC resource calls

### ISSUE THREAD

**Issue by jmmcatee** [jmmcatee/cracklord#15]
The Queue currently calls resource over a standard TCP connection. This needs to be over TLS and ignore certificate issues for the time being.

**Comment by emperorcow** [comment]
@jmmcatee - Please document https://github.com/jmmcatee/cracklord/wiki/Creating-Resource-Certificates so we have this somewhere and it's nice and easy for people.

**Comment by raul5660** [comment]
i'm reading the resource certificate section and its not 100% clear on what server you're suppose to be doing this on?

**Comment by emperorcow** [comment]
@raul5660 So a quick question for you.  Did you use the DEB files to include the queue server and resource server?  Are you running the two of them on different systems, or both on the same?

**Comment by raul5660** [comment]
i'm doing some testing on VMs before I implement on physical boxes, but i have 1 queue server vm and 2 resource servers vms. The queue server is going to be standalone. But I'm not saying that i didn't get it to work. Just saying it wouldn't be clear if someone new was trying to run thru the installation process

**Comment by jmmcatee** [comment]
This is good feedback. I will try and make it more clear. It might make more sense to have one page that is all the certificate work from start to finish with jumps to the resource piece if you have used the .DEB file to get the Queue Server up and running.

**Comment by matt-wiseman** [comment]
Following the guidelines from [this wiki page](https://github.com/jmmcatee/cracklord/wiki/Creating-Resource-Certificates) results in:

`An error occured when trying to add the resource: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs`

Is there anything I can do to fix this?

Also, it should be noted that it appears that any resource name provided during a failed addition is still logged as existing, so any future attempts at adding the same resource must be under a different name. I'm assuming this is unexpected behavior.

Thanks.

**Comment by jmmcatee** [comment]
Matt,

There is a bug where we track a resource that failed to connect. The IP SANS error happens when you attempt to connect via an IP address. You can add IPs to the certificate, but I'll need to update the documentation on how. If you use a hostname for the CN and connect via that, it should work.

**Comment by jmmcatee** [comment]
@matt-wiseman were you able to solve this issue?
