### ISSUE TITLE
Returned parameter div improvements

### ISSUE THREAD

**Issue by jmmcatee** [jmmcatee/cracklord#48]
The div that displays returned parameters should list the first few (4 or 5) then have a more information link. This should pop-up a menu that shows all parameters returned by the job (hopefully without sensitive data) and also provide all the OutputTitle and Data fields as well.

**Comment by emperorcow** [comment]
So I think this needs to be two things, I'm changing the flags around a bit.  I do agree that the way it's presented in the GUI can be greatly improved, I'm thinking with a dialog or popup div of some sort.  I also think that the tools all need to determine what they should return, because I don't believe we should have hashes in this information.  Thoughts?
