### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by jugganuts420** [jmmcatee/cracklord#80]
blacktop blacktop # ./script.deb.sh
Detected operating system as LinuxMint/rafaela.
Checking for curl...
Detected curl...
Installing apt-transport-https... done.
Getting the hostname of this machine...
Found hostname: blacktop
Installing /etc/apt/sources.list.d/emperorcow_cracklord.list...  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Unable to download repo config from: https://packagecloud.io/install/repositories/emperorcow/cracklord/config_file.list?os=LinuxMint&dist=rafaela&name=blacktop&source=script

Please contact support@packagecloud.io and report this.

**Comment by emperorcow** [comment]
I took a look into this, right now we're only building our packages for Ubuntu and Debian.  This is because we're using PackageCloud.io to automatically build out packages.  Sadly, Linux Mint is not supported by PackageCloud, but since Mint is another derivative of Debian, you should be able to do a manual install of the repositories to get it working.  

If you try and follow the instructions here for the manual install: https://packagecloud.io/emperorcow/cracklord/install#manual, can you let us know if you have any further issues?    I think it should work, but I'm not 100% sure.

**Comment by jugganuts420** [comment]
works! thx
